const copy = {
  en:{snapshot:'Verified profile snapshot',snapshotNote:'Registration details come from the third-party verification section; operating figures are supplier-profile disclosures. Reconfirm them for each order.',factLabels:['Established','Registered capital','Profile-listed floor space','On-time dispatch'],whyTitle:'Why work with this supply chain',whyNote:'Service advantages stated in supplier materials; MOQ, pricing and delivery are confirmed for each specification.',strengths:['Product-specific MOQ options','OEM & ODM coordination','Multi-category packaging sourcing','Production-stage follow-up','Luzhou Port logistics coordination'],marketsTitle:'Sales markets shown on the public profile',marketsNote:'The profile reports a domestic-sales majority and a developing export footprint.',marketLabels:['Domestic market','Western Europe','North America','Southeast Asia','Oceania','Other markets'],galleryTitle:'People, materials and production',galleryNote:'Original photographs loaded by the public Alibaba company profile.',galleryCaptions:['Supply-chain office','Raw material inventory','Product design','Quality testing equipment','Printing equipment','Automatic bag production'],libraryTitle:'Documents, separated for review',libraryIntro:'The supplier publishes these documents in one original certificate strip. Each panel is separated below so the details can be inspected.',open:'Open full image',document:'Supplier document',certificateNote:'Supplier-displayed document. Confirm the holder, scope, issuing body and current validity before ordering.',types:{environment:'Environmental management system certificate',quality:'Quality management system certificate',safety:'Occupational health and safety management certificate',network:'Certification-network document',utility:'Utility-model patent certificate',invention:'Invention patent certificate'}},
  zh:{snapshot:'企业档案核验快照',snapshotNote:'登记信息来自第三方核验栏目；经营数据为供应商档案披露。具体订单仍需再次确认。',factLabels:['成立年份','注册资本','档案所列经营面积','准时发货率'],whyTitle:'为什么选择这套供应链协同',whyNote:'以下为供应商资料所述服务优势；起订量、价格与交期需按具体规格确认。',strengths:['按产品协商起订量','OEM 与 ODM 协同','多品类包装采购','生产过程跟进','泸州港物流协调'],marketsTitle:'公开档案展示的销售市场',marketsNote:'档案显示销售仍以内销为主，海外市场正在拓展。',marketLabels:['中国内地','西欧','北美','东南亚','大洋洲','其他市场'],galleryTitle:'团队、材料与生产现场',galleryNote:'以下均为阿里公开公司档案实际加载的原始图片。',galleryCaptions:['供应链办公现场','原材料库存','产品设计','质量检测设备','印刷设备','自动制袋生产'],libraryTitle:'逐份查看证书与文件',libraryIntro:'供应商把这些文件发布在同一张证书原图中；下方已逐份拆开展示，便于查看细节。',open:'查看完整图片',document:'供应商文件',certificateNote:'供应商展示文件。下单前请核实持证主体、适用范围、签发机构与当前有效性。',types:{environment:'环境管理体系认证证书',quality:'质量管理体系认证证书',safety:'职业健康安全管理体系认证证书',network:'认证网络文件',utility:'实用新型专利证书',invention:'发明专利证书'}},
  fr:{snapshot:'Aperçu du profil vérifié',snapshotNote:'Les données d’immatriculation proviennent de la vérification tierce ; les chiffres d’activité sont déclarés dans le profil fournisseur. À reconfirmer pour chaque commande.',factLabels:['Année de création','Capital social','Surface indiquée au profil','Expéditions à temps'],whyTitle:'Pourquoi travailler avec cette chaîne logistique',whyNote:'Avantages présentés par le fournisseur ; MOQ, prix et délais sont confirmés selon le cahier des charges.',strengths:['MOQ selon le produit','Coordination OEM et ODM','Sourcing multicroisé d’emballages','Suivi de la production','Coordination logistique via Luzhou'],marketsTitle:'Marchés indiqués dans le profil public',marketsNote:'Le profil fait état d’une majorité de ventes nationales et d’une présence export en développement.',marketLabels:['Marché intérieur','Europe occidentale','Amérique du Nord','Asie du Sud-Est','Océanie','Autres marchés'],galleryTitle:'Équipe, matières et production',galleryNote:'Photographies originales chargées par le profil public Alibaba.',galleryCaptions:['Bureau de coordination','Stock de matières','Conception produit','Équipement de contrôle','Équipement d’impression','Fabrication automatique de sacs'],libraryTitle:'Documents séparés pour examen',libraryIntro:'Le fournisseur publie ces documents dans une seule bande originale. Chaque panneau est séparé ci-dessous pour faciliter la lecture.',open:'Ouvrir l’image complète',document:'Document fournisseur',certificateNote:'Document présenté par le fournisseur. Vérifiez titulaire, portée, organisme émetteur et validité avant commande.',types:{environment:'Certificat de management environnemental',quality:'Certificat de management de la qualité',safety:'Certificat santé et sécurité au travail',network:'Document du réseau de certification',utility:'Brevet de modèle d’utilité',invention:'Brevet d’invention'}},
  de:{snapshot:'Momentaufnahme des geprüften Profils',snapshotNote:'Registerdaten stammen aus der Drittprüfung; Betriebskennzahlen sind Angaben im Lieferantenprofil. Für jeden Auftrag erneut bestätigen.',factLabels:['Gründungsjahr','Stammkapital','Im Profil genannte Fläche','Pünktlicher Versand'],whyTitle:'Warum mit dieser Lieferkette arbeiten',whyNote:'Vom Lieferanten genannte Vorteile; MOQ, Preis und Lieferzeit werden je Spezifikation bestätigt.',strengths:['Produktspezifische Mindestmengen','OEM- und ODM-Koordination','Beschaffung mehrerer Verpackungsarten','Begleitung der Produktion','Logistikkoordination über Luzhou'],marketsTitle:'Im öffentlichen Profil genannte Märkte',marketsNote:'Das Profil weist überwiegend Inlandsumsatz und eine wachsende Exportpräsenz aus.',marketLabels:['Inlandsmarkt','Westeuropa','Nordamerika','Südostasien','Ozeanien','Weitere Märkte'],galleryTitle:'Team, Materialien und Produktion',galleryNote:'Originalfotos aus dem öffentlichen Alibaba-Unternehmensprofil.',galleryCaptions:['Supply-Chain-Büro','Rohmaterialbestand','Produktdesign','Prüfgerät','Druckanlage','Automatische Beutelproduktion'],libraryTitle:'Dokumente einzeln zur Prüfung',libraryIntro:'Der Lieferant veröffentlicht diese Dokumente in einem Originalstreifen. Jedes Feld ist unten separat dargestellt.',open:'Vollbild öffnen',document:'Lieferantendokument',certificateNote:'Vom Lieferanten gezeigtes Dokument. Inhaber, Geltungsbereich, Aussteller und aktuelle Gültigkeit vor Bestellung prüfen.',types:{environment:'Umweltmanagement-Zertifikat',quality:'Qualitätsmanagement-Zertifikat',safety:'Arbeitsschutzmanagement-Zertifikat',network:'Dokument des Zertifizierungsnetzwerks',utility:'Gebrauchsmusterpatent',invention:'Erfindungspatent'}},
  es:{snapshot:'Resumen del perfil verificado',snapshotNote:'Los datos registrales proceden de la verificación externa; las cifras operativas son declaraciones del perfil del proveedor. Deben reconfirmarse para cada pedido.',factLabels:['Año de constitución','Capital registrado','Superficie indicada','Despachos a tiempo'],whyTitle:'Por qué trabajar con esta cadena de suministro',whyNote:'Ventajas declaradas por el proveedor; MOQ, precio y entrega se confirman para cada especificación.',strengths:['MOQ según el producto','Coordinación OEM y ODM','Abastecimiento de varias categorías','Seguimiento de producción','Coordinación logística por Luzhou'],marketsTitle:'Mercados mostrados en el perfil público',marketsNote:'El perfil informa de una mayoría de ventas nacionales y una presencia exportadora en desarrollo.',marketLabels:['Mercado nacional','Europa Occidental','Norteamérica','Sudeste Asiático','Oceanía','Otros mercados'],galleryTitle:'Equipo, materiales y producción',galleryNote:'Fotografías originales cargadas por el perfil público de Alibaba.',galleryCaptions:['Oficina de coordinación','Inventario de materias primas','Diseño de producto','Equipo de control de calidad','Equipo de impresión','Producción automática de bolsas'],libraryTitle:'Documentos separados para revisión',libraryIntro:'El proveedor publica estos documentos en una única tira original. Cada panel se separa abajo para poder inspeccionarlo.',open:'Abrir imagen completa',document:'Documento del proveedor',certificateNote:'Documento mostrado por el proveedor. Confirme titular, alcance, organismo emisor y vigencia antes de comprar.',types:{environment:'Certificado de gestión ambiental',quality:'Certificado de gestión de calidad',safety:'Certificado de seguridad y salud laboral',network:'Documento de red de certificación',utility:'Patente de modelo de utilidad',invention:'Patente de invención'}},
  it:{snapshot:'Istantanea del profilo verificato',snapshotNote:'I dati di registrazione provengono dalla verifica di terzi; i dati operativi sono dichiarati nel profilo fornitore. Da riconfermare per ogni ordine.',factLabels:['Anno di fondazione','Capitale registrato','Superficie indicata','Spedizioni puntuali'],whyTitle:'Perché lavorare con questa filiera',whyNote:'Vantaggi dichiarati dal fornitore; MOQ, prezzo e consegna vengono confermati per ogni specifica.',strengths:['MOQ in base al prodotto','Coordinamento OEM e ODM','Approvvigionamento multi-categoria','Monitoraggio della produzione','Coordinamento logistico via Luzhou'],marketsTitle:'Mercati indicati nel profilo pubblico',marketsNote:'Il profilo riporta una prevalenza di vendite interne e una presenza export in sviluppo.',marketLabels:['Mercato interno','Europa occidentale','Nord America','Sud-est asiatico','Oceania','Altri mercati'],galleryTitle:'Persone, materiali e produzione',galleryNote:'Fotografie originali caricate dal profilo aziendale pubblico Alibaba.',galleryCaptions:['Ufficio di coordinamento','Scorte di materie prime','Progettazione prodotto','Attrezzatura di controllo','Attrezzatura di stampa','Produzione automatica di borse'],libraryTitle:'Documenti separati per la verifica',libraryIntro:'Il fornitore pubblica questi documenti in un’unica striscia originale. Ogni riquadro è separato qui sotto.',open:'Apri immagine completa',document:'Documento del fornitore',certificateNote:'Documento mostrato dal fornitore. Verificare titolare, ambito, ente emittente e validità prima dell’ordine.',types:{environment:'Certificato di gestione ambientale',quality:'Certificato di gestione della qualità',safety:'Certificato di salute e sicurezza sul lavoro',network:'Documento della rete di certificazione',utility:'Brevetto per modello di utilità',invention:'Brevetto d’invenzione'}},
  ar:{snapshot:'لقطة من ملف الشركة المتحقق منه',snapshotNote:'بيانات التسجيل من قسم التحقق الخارجي، أما مؤشرات التشغيل فهي إفصاحات في ملف المورد. يجب إعادة تأكيدها لكل طلب.',factLabels:['سنة التأسيس','رأس المال المسجل','المساحة المدرجة في الملف','الشحن في الموعد'],whyTitle:'لماذا العمل مع سلسلة التوريد هذه',whyNote:'مزايا يذكرها المورد؛ ويُؤكد الحد الأدنى والسعر والتسليم لكل مواصفة.',strengths:['حد أدنى حسب المنتج','تنسيق OEM وODM','توريد فئات تعبئة متعددة','متابعة مراحل الإنتاج','تنسيق الخدمات اللوجستية عبر لوتشو'],marketsTitle:'الأسواق المعروضة في الملف العام',marketsNote:'يفيد الملف بأن المبيعات المحلية هي الأغلبية مع حضور تصديري آخذ في النمو.',marketLabels:['السوق المحلي','أوروبا الغربية','أمريكا الشمالية','جنوب شرق آسيا','أوقيانوسيا','أسواق أخرى'],galleryTitle:'الفريق والمواد والإنتاج',galleryNote:'صور أصلية حمّلها ملف الشركة العام على علي بابا.',galleryCaptions:['مكتب تنسيق سلسلة التوريد','مخزون المواد الخام','تصميم المنتج','معدات اختبار الجودة','معدات الطباعة','إنتاج الأكياس آلياً'],libraryTitle:'وثائق منفصلة للمراجعة',libraryIntro:'ينشر المورد هذه الوثائق في شريط أصلي واحد. فُصلت كل لوحة أدناه لتسهيل فحص التفاصيل.',open:'فتح الصورة الكاملة',document:'وثيقة المورد',certificateNote:'وثيقة يعرضها المورد. تحقق من صاحبها ونطاقها والجهة المصدرة وصلاحيتها الحالية قبل الطلب.',types:{environment:'شهادة نظام الإدارة البيئية',quality:'شهادة نظام إدارة الجودة',safety:'شهادة إدارة الصحة والسلامة المهنية',network:'وثيقة شبكة الاعتماد',utility:'شهادة براءة نموذج منفعة',invention:'شهادة براءة اختراع'}},
  ru:{snapshot:'Снимок проверенного профиля',snapshotNote:'Регистрационные данные взяты из раздела сторонней проверки; операционные показатели заявлены в профиле поставщика. Их нужно подтвердить для заказа.',factLabels:['Год основания','Уставный капитал','Площадь по данным профиля','Отправка в срок'],whyTitle:'Почему работать с этой цепочкой поставок',whyNote:'Преимущества заявлены поставщиком; MOQ, цена и срок подтверждаются для каждой спецификации.',strengths:['MOQ зависит от товара','Координация OEM и ODM','Закупка разных видов упаковки','Контроль этапов производства','Логистика через Лучжоу'],marketsTitle:'Рынки, указанные в открытом профиле',marketsNote:'Профиль показывает преобладание внутренних продаж и развивающееся экспортное направление.',marketLabels:['Внутренний рынок','Западная Европа','Северная Америка','Юго-Восточная Азия','Океания','Другие рынки'],galleryTitle:'Команда, материалы и производство',galleryNote:'Оригинальные фотографии из открытого профиля компании на Alibaba.',galleryCaptions:['Офис координации','Запас сырья','Дизайн продукции','Испытательное оборудование','Печатное оборудование','Автоматическое производство пакетов'],libraryTitle:'Документы по отдельности',libraryIntro:'Поставщик публикует документы одной исходной лентой. Ниже каждый фрагмент отделён для подробного просмотра.',open:'Открыть полное изображение',document:'Документ поставщика',certificateNote:'Документ представлен поставщиком. Перед заказом проверьте владельца, область, орган выдачи и срок действия.',types:{environment:'Сертификат экологического менеджмента',quality:'Сертификат менеджмента качества',safety:'Сертификат охраны труда и безопасности',network:'Документ сети сертификации',utility:'Патент на полезную модель',invention:'Патент на изобретение'}},
  hi:{snapshot:'सत्यापित प्रोफ़ाइल का सार',snapshotNote:'पंजीकरण विवरण तृतीय-पक्ष सत्यापन से हैं; परिचालन आँकड़े सप्लायर प्रोफ़ाइल में दिए गए दावे हैं। हर ऑर्डर के लिए दोबारा पुष्टि करें।',factLabels:['स्थापना वर्ष','पंजीकृत पूँजी','प्रोफ़ाइल में दिया क्षेत्रफल','समय पर डिस्पैच'],whyTitle:'इस सप्लाई चेन के साथ क्यों काम करें',whyNote:'सप्लायर सामग्री में बताए लाभ; MOQ, कीमत और डिलीवरी हर स्पेसिफिकेशन पर तय होंगे।',strengths:['उत्पाद के अनुसार MOQ','OEM और ODM समन्वय','कई पैकेजिंग श्रेणियों की सोर्सिंग','उत्पादन चरण की निगरानी','लूझोउ पोर्ट लॉजिस्टिक्स समन्वय'],marketsTitle:'सार्वजनिक प्रोफ़ाइल में दिखाए बाज़ार',marketsNote:'प्रोफ़ाइल में घरेलू बिक्री बहुसंख्यक और निर्यात उपस्थिति विकसित होती दिखाई गई है।',marketLabels:['घरेलू बाज़ार','पश्चिमी यूरोप','उत्तरी अमेरिका','दक्षिण-पूर्व एशिया','ओशिनिया','अन्य बाज़ार'],galleryTitle:'टीम, सामग्री और उत्पादन',galleryNote:'सार्वजनिक Alibaba कंपनी प्रोफ़ाइल में लोड हुई मूल तस्वीरें।',galleryCaptions:['सप्लाई-चेन कार्यालय','कच्चे माल का भंडार','उत्पाद डिज़ाइन','गुणवत्ता परीक्षण उपकरण','प्रिंटिंग उपकरण','स्वचालित बैग उत्पादन'],libraryTitle:'समीक्षा के लिए अलग-अलग दस्तावेज़',libraryIntro:'सप्लायर इन्हें एक मूल प्रमाणपत्र स्ट्रिप में प्रकाशित करता है। विवरण देखने के लिए हर पैनल नीचे अलग किया गया है।',open:'पूरी छवि खोलें',document:'सप्लायर दस्तावेज़',certificateNote:'सप्लायर द्वारा प्रदर्शित दस्तावेज़। ऑर्डर से पहले धारक, दायरा, जारीकर्ता और वर्तमान वैधता जाँचें।',types:{environment:'पर्यावरण प्रबंधन प्रमाणपत्र',quality:'गुणवत्ता प्रबंधन प्रमाणपत्र',safety:'व्यावसायिक स्वास्थ्य व सुरक्षा प्रमाणपत्र',network:'प्रमाणन नेटवर्क दस्तावेज़',utility:'यूटिलिटी मॉडल पेटेंट प्रमाणपत्र',invention:'आविष्कार पेटेंट प्रमाणपत्र'}},
  id:{snapshot:'Ringkasan profil terverifikasi',snapshotNote:'Data registrasi berasal dari verifikasi pihak ketiga; angka operasional adalah pengungkapan profil pemasok. Konfirmasikan kembali untuk setiap pesanan.',factLabels:['Tahun berdiri','Modal terdaftar','Luas yang tercantum','Pengiriman tepat waktu'],whyTitle:'Mengapa bekerja dengan rantai pasok ini',whyNote:'Keunggulan yang dinyatakan pemasok; MOQ, harga, dan pengiriman dikonfirmasi per spesifikasi.',strengths:['MOQ sesuai produk','Koordinasi OEM dan ODM','Sumber berbagai kategori kemasan','Pemantauan tahap produksi','Koordinasi logistik melalui Luzhou'],marketsTitle:'Pasar yang ditampilkan di profil publik',marketsNote:'Profil menunjukkan penjualan domestik masih dominan dan pasar ekspor sedang berkembang.',marketLabels:['Pasar domestik','Eropa Barat','Amerika Utara','Asia Tenggara','Oseania','Pasar lainnya'],galleryTitle:'Tim, bahan, dan produksi',galleryNote:'Foto asli yang dimuat oleh profil perusahaan publik Alibaba.',galleryCaptions:['Kantor koordinasi','Persediaan bahan baku','Desain produk','Peralatan uji mutu','Peralatan pencetakan','Produksi tas otomatis'],libraryTitle:'Dokumen terpisah untuk ditinjau',libraryIntro:'Pemasok menerbitkan dokumen ini dalam satu strip asli. Setiap panel dipisahkan di bawah agar detailnya mudah diperiksa.',open:'Buka gambar penuh',document:'Dokumen pemasok',certificateNote:'Dokumen yang ditampilkan pemasok. Konfirmasikan pemegang, cakupan, penerbit, dan masa berlaku sebelum memesan.',types:{environment:'Sertifikat sistem manajemen lingkungan',quality:'Sertifikat sistem manajemen mutu',safety:'Sertifikat kesehatan dan keselamatan kerja',network:'Dokumen jaringan sertifikasi',utility:'Sertifikat paten model utilitas',invention:'Sertifikat paten invensi'}},
};

export const companyFacts = [
  {value:'2018'},
  {value:'RMB 10.2M'},
  {value:'99 m²'},
  {value:'100%'},
];

export const companyMarkets = [80,8,6,3,1,2];

export const companyGallery = [
  '/images/company/factory-tour.jpg',
  '/images/company/raw-materials.jpg',
  '/images/company/product-design.jpg',
  '/images/company/quality-test.jpg',
  '/images/company/printing.jpg',
  '/images/company/bag-production.jpg',
];

const certificateTypes = ['environment','quality','safety','environment','safety','quality','network','utility','utility','utility','invention','quality','utility'];

export const certificateRecords = certificateTypes.map((type,index)=>({
  type,
  image:`/images/certificates/document-${String(index + 1).padStart(2,'0')}.png`,
}));

export const extraCopy = language => copy[language] || copy.en;
