export const contentPageSlugs = [
  'company',
  'capabilities/custom-packaging',
  'capabilities/production',
  'quality',
  'products/featured',
  'request-quote',
];

const pagePresentation = {
  company: { image:'/images/alibaba/company-overview.avif', layout:'company' },
  'capabilities/custom-packaging': { image:'/images/alibaba/custom-packaging.avif', layout:'capability' },
  'capabilities/production': { image:'/images/alibaba/production-equipment.jpg', layout:'production' },
  quality: { image:'/images/alibaba/certificates.avif', layout:'quality' },
  'products/featured': { image:'/images/alibaba/main-products.avif', layout:'products' },
  'request-quote': { image:'/images/alibaba/customization-process.avif', layout:'quote' },
};

const copy = {
  en: {
    company: ['Company profile','A supply-chain partner for custom packaging','Luzhou Transportation & Logistics Supply Chain Management Co., Ltd. coordinates material sourcing, packaging customization, inspection and international delivery from Luzhou, Sichuan.', ['Registered in China; business-license information was checked on the supplier profile.','Registered capital shown by the verification provider: RMB 10.2 million.','Luzhou Port supports access to water, rail and road freight routes.','The public Alibaba profile lists Western Europe, North America, Southeast Asia and Oceania among its overseas markets.'],'Company profile and packaging categories presented by the supplier'],
    'capabilities/custom-packaging': ['Custom packaging','Built around your product and brand','Start with the intended use, dimensions, quantity and artwork. We coordinate the material, structure, printing, handles and finishing into a sample-ready specification.', ['Minor, drawing-based, sample-based and full customization are listed as available.','Core materials include paper, paperboard, kraft and non-woven options.','Printing and finish options are confirmed against the chosen structure and order volume.','A physical sample should be approved before volume production.'],'Custom paper, gift and non-woven packaging bags'],
    'capabilities/production': ['Production process','A clear path from artwork to shipment','The supplier materials show printing, laminating, hot stamping, cutting and automatic bag-making processes. We turn those capabilities into a controlled order workflow.', ['Requirements and artwork review','Quotation, material proposal and sample confirmation','Production scheduling with in-process quality checks','Packing, final confirmation and shipment coordination'],'Production and packaging equipment shown by the supplier'],
    quality: ['Quality assurance','Confirm the details that matter before production','Quality starts with a written specification and an approved sample. Material, dimensions, print, structure and packing requirements should be checked at defined stages.', ['Confirm certificate scope, issuing body and validity for the exact product.','Approve color, material, dimensions and load-bearing expectations on the sample.','Use in-process checks for printing, lamination, cutting and bag forming.','Complete final inspection and packing verification before shipment.'],'Certificates and quality documents displayed by the supplier'],
    'products/featured': ['Featured packaging','The categories buyers ask for most','A focused selection of customizable paper bags, non-woven bags, gift packaging, boxes and retail carriers. Film products are intentionally not prioritized here.', ['Paper and kraft carrier bags','Reusable non-woven shopping bags','Gift bags and paper gift boxes','Mailer boxes and selected retail packaging'],'Main packaging categories displayed by the supplier'],
    'request-quote': ['Request a quote','Turn your packaging brief into a workable specification','Share the product type, size, quantity, intended use and artwork status. We will use that information to frame the questions required for a supplier quotation.', ['Product and intended use','Finished dimensions and estimated quantity','Material, color, handles and printing requirements','Target delivery market and preferred timing'],'Supplier customization and order process'],
  },
  zh: {
    company: ['公司介绍','立足泸州的定制包装供应链伙伴','泸州交通物流供应链管理有限公司依托四川泸州的物流资源，协同原材料采购、包装定制、质量检查与国际交付。', ['企业已在中国登记，营业执照信息已在供应商档案中核验。','核验服务商展示的注册资本为人民币 1,020 万元。','依托泸州港，可衔接水运、铁路与公路运输。','阿里公开档案列出的海外市场包括西欧、北美、东南亚和大洋洲。'],'供应商展示的公司介绍与包装品类'],
    'capabilities/custom-packaging': ['包装定制','围绕产品与品牌，把需求变成可打样规格','从用途、尺寸、数量和设计稿开始，协同确定材料、结构、印刷、提手与表面工艺，形成可报价、可打样的方案。', ['支持轻度定制、按图定制、按样定制与深度定制。','核心材料包括纸张、纸板、牛皮纸与无纺布。','印刷与表面工艺需结合结构和订单量确认。','量产前应确认实物样品。'],'定制纸袋、礼品袋与无纺布袋'],
    'capabilities/production': ['生产流程','从设计稿到出货，每一步更清楚','供应商资料展示了印刷、复合、烫印、裁切与自动制袋等工序。我们将这些环节组织成可跟进的订单流程。', ['需求与设计稿审核','报价、选材与样品确认','排产并进行过程质量检查','包装、终检与出货协调'],'供应商展示的包装生产设备'],
    quality: ['质量保障','在生产前，把关键细节确认清楚','质量从书面规格和确认样开始。材料、尺寸、印刷、结构与装箱要求应在明确的节点逐项检查。', ['确认每份证书对具体产品的适用范围、签发机构与有效期。','在样品阶段确认颜色、材料、尺寸和承重预期。','对印刷、复合、裁切和成袋实施过程检查。','出货前完成成品检验与装箱核对。'],'供应商展示的证书与质量文件'],
    'products/featured': ['精选包装','聚焦采购方最常询问的包装品类','精选可定制纸袋、无纺布袋、礼品包装、纸盒与零售手提包装；薄膜类产品不作为本页重点。', ['纸质与牛皮纸手提袋','可重复使用无纺布购物袋','礼品袋与纸质礼盒','邮寄盒及精选零售包装'],'供应商展示的主要包装品类'],
    'request-quote': ['获取报价','把包装需求变成可执行的规格','请提供产品类型、尺寸、数量、用途和设计稿状态。我们会据此整理供应商报价所需的关键问题。', ['产品类型与使用场景','成品尺寸与预计数量','材料、颜色、提手和印刷要求','目标市场与期望交期'],'供应商定制与下单流程'],
  },
  fr: {
    company: ["Profil de l’entreprise",'Votre partenaire de chaîne logistique pour les emballages sur mesure',"Luzhou Transportation & Logistics Supply Chain Management Co., Ltd. coordonne l’approvisionnement, la personnalisation, le contrôle et la livraison internationale depuis Luzhou, dans le Sichuan.", ["L’entreprise est enregistrée en Chine et les données de sa licence ont été vérifiées sur le profil fournisseur.",'Capital social indiqué par le prestataire de vérification : 10,2 millions RMB.','Le port de Luzhou donne accès aux liaisons fluviales, ferroviaires et routières.',"Le profil public Alibaba mentionne notamment l’Europe occidentale, l’Amérique du Nord, l’Asie du Sud-Est et l’Océanie."],"Présentation de l’entreprise et catégories d’emballages publiées par le fournisseur"],
    'capabilities/custom-packaging': ['Emballage sur mesure','Conçu autour de votre produit et de votre marque',"À partir de l’usage, des dimensions, de la quantité et du fichier graphique, nous coordonnons matière, structure, impression, poignées et finitions.", ['Personnalisation légère, sur plan, sur échantillon ou complète.','Papier, carton, kraft et non-tissé parmi les principales matières.','Impressions et finitions à confirmer selon la structure et le volume.','Un échantillon physique doit être validé avant la série.'],'Sacs personnalisés en papier, cadeau et non-tissé'],
    'capabilities/production': ['Processus de production','Un parcours clair du fichier à l’expédition','Les supports du fournisseur montrent des étapes d’impression, de pelliculage, de dorure, de découpe et de fabrication automatique des sacs.', ['Revue du besoin et des fichiers','Devis, choix matière et validation de l’échantillon','Planification et contrôles en cours de production','Emballage, contrôle final et coordination du transport'],'Équipements de production présentés par le fournisseur'],
    quality: ['Assurance qualité','Valider les points essentiels avant la production','La qualité commence par un cahier des charges écrit et un échantillon approuvé. Matière, dimensions, impression, structure et conditionnement sont contrôlés à des étapes définies.', ['Vérifier portée, organisme émetteur et validité de chaque certificat.','Valider couleur, matière, dimensions et résistance sur échantillon.','Contrôler impression, pelliculage, découpe et formage.','Effectuer le contrôle final et vérifier le conditionnement avant expédition.'],'Certificats et documents qualité affichés par le fournisseur'],
    'products/featured': ['Emballages à la une','Les catégories les plus demandées','Une sélection ciblée de sacs en papier, sacs non-tissés, emballages cadeaux, boîtes et sacs de vente. Les films ne sont pas prioritaires ici.', ['Sacs en papier et kraft','Sacs shopping réutilisables en non-tissé','Sacs et boîtes cadeaux','Boîtes postales et emballages de vente sélectionnés'],'Principales catégories présentées par le fournisseur'],
    'request-quote': ['Demander un devis','Transformez votre besoin en spécification exploitable',"Indiquez le type d’emballage, les dimensions, la quantité, l’usage et l’état du fichier graphique pour préparer une demande de prix précise.", ['Produit et usage prévu','Dimensions finies et quantité estimée','Matière, couleur, poignées et impression','Marché de livraison et délai souhaité'],'Processus de personnalisation et de commande'],
  },
  de: {
    company: ['Unternehmen','Ihr Supply-Chain-Partner für individuelle Verpackungen','Luzhou Transportation & Logistics Supply Chain Management Co., Ltd. koordiniert Materialbeschaffung, Individualisierung, Prüfung und internationale Lieferung aus Luzhou in Sichuan.', ['Das Unternehmen ist in China registriert; die Gewerbedaten wurden im Lieferantenprofil geprüft.','Vom Prüfdienst ausgewiesenes Stammkapital: 10,2 Mio. RMB.','Der Hafen Luzhou bindet Wasser-, Schienen- und Straßentransporte an.','Das öffentliche Alibaba-Profil nennt Westeuropa, Nordamerika, Südostasien und Ozeanien als Auslandsmärkte.'],'Unternehmensprofil und Verpackungskategorien des Lieferanten'],
    'capabilities/custom-packaging': ['Individuelle Verpackung','Auf Produkt und Marke zugeschnitten','Aus Einsatzzweck, Maßen, Menge und Druckdaten koordinieren wir Material, Konstruktion, Druck, Griffe und Veredelung zu einer bemusterbaren Spezifikation.', ['Kleine Anpassungen sowie Zeichnungs-, Muster- und Vollindividualisierung.','Papier, Karton, Kraftpapier und Vlies als Kernmaterialien.','Druck und Veredelung werden passend zu Konstruktion und Menge bestätigt.','Vor der Serie sollte ein physisches Muster freigegeben werden.'],'Individuelle Papier-, Geschenk- und Vliestaschen'],
    'capabilities/production': ['Produktionsprozess','Ein klarer Weg von Druckdaten bis Versand','Die Lieferantenunterlagen zeigen Druck, Laminierung, Heißprägung, Zuschnitt und automatische Beutelherstellung.', ['Anforderungs- und Datenprüfung','Angebot, Materialvorschlag und Musterfreigabe','Produktionsplanung und laufende Qualitätskontrolle','Verpackung, Endkontrolle und Versandkoordination'],'Vom Lieferanten gezeigte Produktionsanlagen'],
    quality: ['Qualitätssicherung','Wichtige Details vor Produktionsbeginn bestätigen','Qualität beginnt mit einer schriftlichen Spezifikation und einem freigegebenen Muster. Material, Maße, Druck, Konstruktion und Verpackung werden an festgelegten Punkten geprüft.', ['Geltungsbereich, Aussteller und Laufzeit jedes Zertifikats prüfen.','Farbe, Material, Maße und Belastbarkeit am Muster freigeben.','Druck, Laminierung, Zuschnitt und Formgebung im Prozess kontrollieren.','Endkontrolle und Verpackungsprüfung vor Versand abschließen.'],'Vom Lieferanten gezeigte Zertifikate und Qualitätsunterlagen'],
    'products/featured': ['Ausgewählte Verpackungen','Die meistgefragten Kategorien','Eine fokussierte Auswahl an Papier- und Vliestaschen, Geschenkverpackungen, Kartons und Tragetaschen. Folien stehen hier bewusst nicht im Mittelpunkt.', ['Papier- und Kraftpapiertaschen','Wiederverwendbare Vliestragetaschen','Geschenktaschen und Geschenkboxen','Versandkartons und ausgewählte Verkaufsverpackungen'],'Wichtigste Verpackungskategorien des Lieferanten'],
    'request-quote': ['Angebot anfragen','Aus Ihrem Briefing wird eine belastbare Spezifikation','Nennen Sie Produkttyp, Maße, Menge, Verwendung und Stand der Druckdaten. Damit bereiten wir die nötigen Fragen für ein Lieferantenangebot vor.', ['Produkt und Verwendungszweck','Fertigmaße und geschätzte Menge','Material, Farbe, Griffe und Druck','Zielmarkt und gewünschter Termin'],'Individualisierungs- und Bestellablauf'],
  },
  es: {
    company: ['Perfil de la empresa','Un socio de cadena de suministro para embalaje personalizado','Luzhou Transportation & Logistics Supply Chain Management Co., Ltd. coordina materiales, personalización, inspección y entrega internacional desde Luzhou, Sichuan.', ['Empresa registrada en China; los datos de la licencia se comprobaron en el perfil del proveedor.','Capital registrado indicado por el verificador: 10,2 millones de RMB.','El puerto de Luzhou conecta transporte fluvial, ferroviario y por carretera.','El perfil público de Alibaba cita Europa Occidental, Norteamérica, Sudeste Asiático y Oceanía entre sus mercados exteriores.'],'Perfil de empresa y categorías publicadas por el proveedor'],
    'capabilities/custom-packaging': ['Embalaje personalizado','Diseñado para su producto y su marca','Partimos del uso, medidas, cantidad y diseño para coordinar material, estructura, impresión, asas y acabados en una especificación lista para muestra.', ['Personalización menor, por plano, por muestra y completa.','Papel, cartón, kraft y tejido no tejido como materiales principales.','Impresión y acabados se confirman según estructura y volumen.','Conviene aprobar una muestra física antes de producir.'],'Bolsas personalizadas de papel, regalo y tejido no tejido'],
    'capabilities/production': ['Proceso de producción','Un recorrido claro del diseño al envío','Los materiales del proveedor muestran impresión, laminado, estampado, corte y fabricación automática de bolsas.', ['Revisión de requisitos y arte final','Cotización, propuesta de material y muestra','Planificación y controles durante la producción','Embalaje, inspección final y coordinación del envío'],'Equipos de producción mostrados por el proveedor'],
    quality: ['Garantía de calidad','Confirme lo importante antes de producir','La calidad comienza con una especificación escrita y una muestra aprobada. Material, medidas, impresión, estructura y embalaje se revisan en etapas definidas.', ['Confirmar alcance, emisor y vigencia de cada certificado.','Aprobar color, material, medidas y resistencia en la muestra.','Controlar impresión, laminado, corte y formado.','Completar inspección final y revisión del embalaje antes del envío.'],'Certificados y documentos de calidad mostrados por el proveedor'],
    'products/featured': ['Embalajes destacados','Las categorías que más solicitan los compradores','Selección de bolsas de papel y no tejido, embalaje de regalo, cajas y bolsas comerciales. Las películas no son una prioridad aquí.', ['Bolsas de papel y kraft','Bolsas reutilizables de tejido no tejido','Bolsas y cajas de regalo','Cajas postales y embalaje comercial seleccionado'],'Principales categorías mostradas por el proveedor'],
    'request-quote': ['Solicitar cotización','Convierta su idea en una especificación viable','Indique tipo, medidas, cantidad, uso y estado del diseño. Usaremos esos datos para preparar las preguntas necesarias para cotizar.', ['Producto y uso previsto','Medidas finales y cantidad estimada','Material, color, asas e impresión','Mercado de destino y plazo deseado'],'Proceso de personalización y pedido'],
  },
  it: {
    company: ["Profilo dell’azienda",'Un partner di filiera per il packaging personalizzato','Luzhou Transportation & Logistics Supply Chain Management Co., Ltd. coordina approvvigionamento, personalizzazione, controllo e consegna internazionale da Luzhou, Sichuan.', ["Azienda registrata in Cina; i dati della licenza sono stati verificati nel profilo fornitore.",'Capitale registrato indicato dal servizio di verifica: 10,2 milioni di RMB.','Il porto di Luzhou collega trasporto fluviale, ferroviario e stradale.','Il profilo pubblico Alibaba indica Europa occidentale, Nord America, Sud-est asiatico e Oceania tra i mercati esteri.'],'Profilo aziendale e categorie presentate dal fornitore'],
    'capabilities/custom-packaging': ['Packaging personalizzato','Pensato per il prodotto e per il marchio',"Da uso, dimensioni, quantità e grafica coordiniamo materiale, struttura, stampa, manici e finiture in una specifica pronta per il campione.", ['Personalizzazione leggera, da disegno, da campione e completa.','Carta, cartoncino, kraft e tessuto non tessuto tra i materiali principali.','Stampa e finiture vengono confermate in base a struttura e volume.','Prima della produzione è opportuno approvare un campione fisico.'],'Borse personalizzate in carta, regalo e tessuto non tessuto'],
    'capabilities/production': ['Processo produttivo','Un percorso chiaro dalla grafica alla spedizione','I materiali del fornitore mostrano stampa, laminazione, stampa a caldo, taglio e produzione automatica delle borse.', ['Revisione di requisiti e file grafici','Preventivo, proposta materiali e conferma campione','Pianificazione e controlli in produzione','Imballaggio, controllo finale e spedizione'],'Attrezzature produttive mostrate dal fornitore'],
    quality: ['Garanzia di qualità','Confermare i dettagli importanti prima di produrre','La qualità parte da una specifica scritta e da un campione approvato. Materiale, dimensioni, stampa, struttura e imballaggio vanno controllati in fasi definite.', ['Verificare ambito, ente emittente e validità di ogni certificato.','Approvare colore, materiale, dimensioni e resistenza sul campione.','Controllare stampa, laminazione, taglio e formatura.','Eseguire controllo finale e verifica imballaggio prima della spedizione.'],'Certificati e documenti qualità mostrati dal fornitore'],
    'products/featured': ['Packaging in evidenza','Le categorie più richieste','Una selezione mirata di borse in carta e tessuto non tessuto, confezioni regalo, scatole e shopper. I film non sono prioritari.', ['Borse in carta e kraft','Shopper riutilizzabili in tessuto non tessuto','Borse e scatole regalo','Scatole postali e packaging retail selezionato'],'Principali categorie mostrate dal fornitore'],
    'request-quote': ['Richiedi un preventivo','Trasforma il brief in una specifica realizzabile','Comunica tipologia, dimensioni, quantità, uso e stato della grafica. Useremo questi dati per preparare una richiesta di preventivo completa.', ['Prodotto e uso previsto','Dimensioni finite e quantità stimata','Materiale, colore, manici e stampa','Mercato di consegna e tempistica'],'Processo di personalizzazione e ordine'],
  },
  ar: {
    company: ['نبذة عن الشركة','شريك لسلسلة توريد العبوات المخصصة','تنسّق شركة لوتشو لإدارة سلسلة توريد النقل والخدمات اللوجستية شراء المواد وتخصيص العبوات والفحص والتسليم الدولي من لوتشو في سيتشوان.', ['الشركة مسجلة في الصين، وقد تم التحقق من بيانات الرخصة في ملف المورد.','رأس المال المسجل المعروض من جهة التحقق: 10.2 مليون يوان صيني.','يربط ميناء لوتشو بين النقل النهري والسكك الحديدية والطرق.','يذكر ملف علي بابا العام أوروبا الغربية وأمريكا الشمالية وجنوب شرق آسيا وأوقيانوسيا ضمن الأسواق الخارجية.'],'نبذة الشركة وفئات العبوات التي يعرضها المورد'],
    'capabilities/custom-packaging': ['عبوات مخصصة','مصممة حول منتجك وعلامتك','نبدأ بالاستخدام والمقاسات والكمية والتصميم، ثم ننسّق الخامة والبنية والطباعة والمقابض والتشطيبات في مواصفة جاهزة للعينة.', ['تخصيص بسيط أو حسب الرسم أو العينة أو تخصيص كامل.','الورق والكرتون وورق كرافت والقماش غير المنسوج من الخامات الأساسية.','تُؤكد الطباعة والتشطيبات بحسب البنية والكمية.','يجب اعتماد عينة فعلية قبل الإنتاج الكمي.'],'أكياس ورقية وهدايا وغير منسوجة مخصصة'],
    'capabilities/production': ['عملية الإنتاج','مسار واضح من التصميم إلى الشحن','تعرض مواد المورد عمليات الطباعة والتصفيح والختم الحراري والقص والتصنيع الآلي للأكياس.', ['مراجعة المتطلبات وملفات التصميم','عرض السعر واقتراح الخامة واعتماد العينة','جدولة الإنتاج وفحوص الجودة أثناءه','التعبئة والفحص النهائي وتنسيق الشحن'],'معدات إنتاج العبوات المعروضة من المورد'],
    quality: ['ضمان الجودة','تأكيد التفاصيل المهمة قبل الإنتاج','تبدأ الجودة بمواصفة مكتوبة وعينة معتمدة. تُفحص الخامة والمقاسات والطباعة والبنية والتعبئة في مراحل محددة.', ['التحقق من نطاق كل شهادة والجهة المصدرة وصلاحيتها.','اعتماد اللون والخامة والمقاسات ومتطلبات التحمل على العينة.','فحص الطباعة والتصفيح والقص وتشكيل الأكياس أثناء الإنتاج.','إتمام الفحص النهائي ومراجعة التعبئة قبل الشحن.'],'الشهادات ووثائق الجودة التي يعرضها المورد'],
    'products/featured': ['عبوات مختارة','الفئات الأكثر طلباً لدى المشترين','تشكيلة مركزة من الأكياس الورقية وغير المنسوجة وعبوات الهدايا والصناديق وأكياس البيع. لا نعطي أولوية لمنتجات الأغشية هنا.', ['أكياس ورقية وكرافت','أكياس تسوق غير منسوجة قابلة لإعادة الاستخدام','أكياس وصناديق هدايا','صناديق شحن وعبوات بيع مختارة'],'فئات العبوات الرئيسية التي يعرضها المورد'],
    'request-quote': ['اطلب عرض سعر','حوّل موجزك إلى مواصفة قابلة للتنفيذ','شارك نوع العبوة والمقاسات والكمية والاستخدام وحالة التصميم، لنحدد المعلومات اللازمة لعرض سعر دقيق.', ['المنتج والاستخدام المقصود','المقاسات النهائية والكمية التقديرية','الخامة واللون والمقابض والطباعة','سوق التسليم والموعد المفضل'],'عملية التخصيص والطلب لدى المورد'],
  },
  ru: {
    company: ['О компании','Партнёр по цепочке поставок индивидуальной упаковки','Luzhou Transportation & Logistics Supply Chain Management Co., Ltd. координирует закупку материалов, изготовление упаковки, контроль и международную доставку из Лучжоу, провинция Сычуань.', ['Компания зарегистрирована в Китае; данные лицензии проверены в профиле поставщика.','Указанный проверяющей организацией уставный капитал — 10,2 млн юаней.','Порт Лучжоу обеспечивает доступ к водным, железнодорожным и автомобильным маршрутам.','В публичном профиле Alibaba среди зарубежных рынков указаны Западная Европа, Северная Америка, Юго-Восточная Азия и Океания.'],'Профиль компании и категории упаковки поставщика'],
    'capabilities/custom-packaging': ['Упаковка на заказ','Под ваш продукт и бренд','На основе назначения, размеров, тиража и макета мы согласуем материал, конструкцию, печать, ручки и отделку и готовим спецификацию для образца.', ['Небольшие изменения, изготовление по чертежу, образцу или полная кастомизация.','Основные материалы: бумага, картон, крафт и нетканое полотно.','Печать и отделка подтверждаются с учётом конструкции и объёма.','До запуска тиража следует утвердить физический образец.'],'Бумажные, подарочные и нетканые пакеты на заказ'],
    'capabilities/production': ['Производственный процесс','Понятный путь от макета до отгрузки','В материалах поставщика показаны печать, ламинирование, горячее тиснение, резка и автоматическое изготовление пакетов.', ['Проверка требований и макета','Расчёт, подбор материала и утверждение образца','Планирование производства и текущий контроль','Упаковка, финальная проверка и организация отгрузки'],'Оборудование, показанное поставщиком'],
    quality: ['Обеспечение качества','Согласуйте важные детали до производства','Качество начинается с письменной спецификации и утверждённого образца. Материал, размеры, печать, конструкция и упаковка проверяются по этапам.', ['Проверить область действия, орган выдачи и срок каждого сертификата.','Утвердить цвет, материал, размеры и ожидаемую прочность по образцу.','Контролировать печать, ламинирование, резку и формование.','Провести финальную инспекцию и проверку упаковки до отгрузки.'],'Сертификаты и документы качества поставщика'],
    'products/featured': ['Избранная упаковка','Самые востребованные категории','Подборка бумажных и нетканых пакетов, подарочной упаковки, коробок и торговых сумок. Плёночная продукция здесь не является приоритетом.', ['Бумажные и крафт-пакеты','Многоразовые нетканые сумки','Подарочные пакеты и коробки','Почтовые коробки и отдельные виды торговой упаковки'],'Основные категории упаковки поставщика'],
    'request-quote': ['Запросить расчёт','Превратите задачу в рабочую спецификацию','Укажите тип упаковки, размеры, количество, назначение и готовность макета. Эти данные помогут подготовить точный запрос поставщику.', ['Продукт и назначение','Готовые размеры и примерный тираж','Материал, цвет, ручки и печать','Рынок доставки и желаемый срок'],'Процесс персонализации и заказа'],
  },
  hi: {
    company: ['कंपनी परिचय','कस्टम पैकेजिंग के लिए सप्लाई-चेन पार्टनर','Luzhou Transportation & Logistics Supply Chain Management Co., Ltd. सिचुआन के लूझोउ से सामग्री खरीद, पैकेजिंग कस्टमाइज़ेशन, निरीक्षण और अंतरराष्ट्रीय डिलीवरी का समन्वय करती है।', ['कंपनी चीन में पंजीकृत है; व्यवसाय लाइसेंस की जानकारी सप्लायर प्रोफ़ाइल पर सत्यापित की गई है।','सत्यापन प्रदाता के अनुसार पंजीकृत पूंजी RMB 10.2 मिलियन है।','लूझोउ पोर्ट जल, रेल और सड़क माल ढुलाई से जुड़ता है।','सार्वजनिक Alibaba प्रोफ़ाइल में पश्चिमी यूरोप, उत्तरी अमेरिका, दक्षिण-पूर्व एशिया और ओशिनिया विदेशी बाज़ारों में शामिल हैं।'],'सप्लायर द्वारा प्रस्तुत कंपनी और पैकेजिंग श्रेणियाँ'],
    'capabilities/custom-packaging': ['कस्टम पैकेजिंग','आपके उत्पाद और ब्रांड के अनुसार','उपयोग, आकार, मात्रा और आर्टवर्क से शुरू कर हम सामग्री, संरचना, प्रिंटिंग, हैंडल और फिनिश को नमूना-तैयार स्पेसिफिकेशन में समन्वित करते हैं।', ['हल्का, ड्रॉइंग-आधारित, नमूना-आधारित और पूर्ण कस्टमाइज़ेशन उपलब्ध।','मुख्य सामग्री में पेपर, पेपरबोर्ड, क्राफ्ट और नॉन-वोवन विकल्प शामिल।','प्रिंट और फिनिश की पुष्टि संरचना और मात्रा के अनुसार होती है।','बड़े उत्पादन से पहले भौतिक नमूना मंज़ूर करें।'],'कस्टम पेपर, गिफ्ट और नॉन-वोवन बैग'],
    'capabilities/production': ['उत्पादन प्रक्रिया','आर्टवर्क से शिपमेंट तक स्पष्ट क्रम','सप्लायर सामग्री में प्रिंटिंग, लैमिनेशन, हॉट स्टैम्पिंग, कटिंग और ऑटोमैटिक बैग निर्माण दिखाया गया है।', ['आवश्यकताओं और आर्टवर्क की समीक्षा','कोटेशन, सामग्री सुझाव और नमूना पुष्टि','उत्पादन योजना और प्रक्रिया के दौरान गुणवत्ता जाँच','पैकिंग, अंतिम पुष्टि और शिपमेंट समन्वय'],'सप्लायर द्वारा दिखाए गए उत्पादन उपकरण'],
    quality: ['गुणवत्ता आश्वासन','उत्पादन से पहले जरूरी बातें पक्की करें','गुणवत्ता लिखित स्पेसिफिकेशन और स्वीकृत नमूने से शुरू होती है। सामग्री, आकार, प्रिंट, संरचना और पैकिंग को तय चरणों पर जाँचना चाहिए।', ['हर प्रमाणपत्र का दायरा, जारीकर्ता और वैधता जाँचें।','नमूने पर रंग, सामग्री, आकार और भार अपेक्षा मंज़ूर करें।','प्रिंटिंग, लैमिनेशन, कटिंग और बैग फॉर्मिंग की प्रक्रिया जाँच करें।','शिपमेंट से पहले अंतिम निरीक्षण और पैकिंग सत्यापन पूरा करें।'],'सप्लायर द्वारा दिखाए गए प्रमाणपत्र और गुणवत्ता दस्तावेज़'],
    'products/featured': ['चुनिंदा पैकेजिंग','खरीदारों की सबसे अधिक माँग वाली श्रेणियाँ','कस्टम पेपर बैग, नॉन-वोवन बैग, गिफ्ट पैकेजिंग, बॉक्स और रिटेल कैरियर का चुना हुआ संग्रह। फ़िल्म उत्पाद यहाँ प्राथमिकता नहीं हैं।', ['पेपर और क्राफ्ट कैरियर बैग','दोबारा उपयोग योग्य नॉन-वोवन शॉपिंग बैग','गिफ्ट बैग और पेपर गिफ्ट बॉक्स','मेलर बॉक्स और चुनिंदा रिटेल पैकेजिंग'],'सप्लायर की मुख्य पैकेजिंग श्रेणियाँ'],
    'request-quote': ['कोटेशन माँगें','अपने पैकेजिंग ब्रीफ़ को व्यावहारिक स्पेसिफिकेशन बनाएँ','उत्पाद प्रकार, आकार, मात्रा, उपयोग और आर्टवर्क की स्थिति साझा करें। इससे सप्लायर को सही कोटेशन देने के लिए आवश्यक सवाल तैयार होंगे।', ['उत्पाद और उपयोग','तैयार आकार और अनुमानित मात्रा','सामग्री, रंग, हैंडल और प्रिंटिंग','डिलीवरी बाज़ार और पसंदीदा समय'],'सप्लायर कस्टमाइज़ेशन और ऑर्डर प्रक्रिया'],
  },
  id: {
    company: ['Profil perusahaan','Mitra rantai pasok untuk kemasan khusus','Luzhou Transportation & Logistics Supply Chain Management Co., Ltd. mengoordinasikan pengadaan bahan, kustomisasi kemasan, pemeriksaan, dan pengiriman internasional dari Luzhou, Sichuan.', ['Perusahaan terdaftar di Tiongkok; data izin usaha telah diperiksa pada profil pemasok.','Modal terdaftar yang ditampilkan penyedia verifikasi: RMB 10,2 juta.','Pelabuhan Luzhou terhubung dengan angkutan sungai, kereta, dan jalan raya.','Profil publik Alibaba mencantumkan Eropa Barat, Amerika Utara, Asia Tenggara, dan Oseania sebagai pasar luar negeri.'],'Profil perusahaan dan kategori kemasan dari pemasok'],
    'capabilities/custom-packaging': ['Kemasan khusus','Dibuat sesuai produk dan merek Anda','Dimulai dari fungsi, ukuran, jumlah, dan desain, kami mengoordinasikan bahan, struktur, cetak, pegangan, dan finishing menjadi spesifikasi siap sampel.', ['Tersedia kustomisasi ringan, berdasarkan gambar, berdasarkan sampel, dan penuh.','Bahan utama meliputi kertas, paperboard, kraft, dan non-woven.','Cetak dan finishing dikonfirmasi sesuai struktur dan volume pesanan.','Sampel fisik sebaiknya disetujui sebelum produksi massal.'],'Tas kertas, hadiah, dan non-woven khusus'],
    'capabilities/production': ['Proses produksi','Alur jelas dari desain hingga pengiriman','Materi pemasok menampilkan proses cetak, laminasi, hot stamping, pemotongan, dan pembuatan tas otomatis.', ['Pemeriksaan kebutuhan dan desain','Penawaran, usulan bahan, dan persetujuan sampel','Penjadwalan produksi serta pemeriksaan selama proses','Pengemasan, pemeriksaan akhir, dan koordinasi pengiriman'],'Peralatan produksi yang ditampilkan pemasok'],
    quality: ['Jaminan kualitas','Pastikan detail penting sebelum produksi','Kualitas dimulai dari spesifikasi tertulis dan sampel yang disetujui. Bahan, ukuran, cetak, struktur, dan pengemasan diperiksa pada tahap yang ditentukan.', ['Periksa cakupan, penerbit, dan masa berlaku setiap sertifikat.','Setujui warna, bahan, ukuran, dan kebutuhan daya tahan pada sampel.','Lakukan pemeriksaan proses untuk cetak, laminasi, potong, dan pembentukan tas.','Selesaikan inspeksi akhir dan verifikasi kemasan sebelum pengiriman.'],'Sertifikat dan dokumen kualitas yang ditampilkan pemasok'],
    'products/featured': ['Kemasan unggulan','Kategori yang paling sering dicari pembeli','Pilihan tas kertas, tas non-woven, kemasan hadiah, kotak, dan tas ritel yang dapat disesuaikan. Produk film tidak diprioritaskan di sini.', ['Tas kertas dan kraft','Tas belanja non-woven yang dapat digunakan kembali','Tas hadiah dan kotak hadiah kertas','Kotak pengiriman dan kemasan ritel pilihan'],'Kategori kemasan utama dari pemasok'],
    'request-quote': ['Minta penawaran','Ubah brief kemasan menjadi spesifikasi yang siap dikerjakan','Sampaikan jenis produk, ukuran, jumlah, penggunaan, dan status desain. Informasi ini membantu menyiapkan pertanyaan yang diperlukan untuk penawaran pemasok.', ['Produk dan tujuan penggunaan','Ukuran jadi dan perkiraan jumlah','Bahan, warna, pegangan, dan cetak','Pasar tujuan dan waktu yang diinginkan'],'Proses kustomisasi dan pemesanan pemasok'],
  },
};

export function getContentPage(slug, language) {
  const localized = copy[language]?.[slug] || copy.en[slug];
  if (!localized || !pagePresentation[slug]) return null;
  const [eyebrow, title, description, points, imageAlt] = localized;
  return { slug, eyebrow, title, description, points, imageAlt, ...pagePresentation[slug] };
}
