import allProducts from './data/all-products.js';
import { initLanguage, t, getLanguage, escapeHtml as esc, number, languageSwitch } from './i18n.js';
import { getContentPage } from './content-pages.js';
import { entityFromLocation } from './seo-routes.js';
import { paperIds, productTitle, imagePath, productLink, categoryLink, supplierUrl, wordmark, metadata, copyMessage, formStatus, emailError, route, footer } from './site.js';

const ui = {
  en:{source:'Original supplier material',notice:'These images were downloaded from the supplier’s public Alibaba storefront at their original loaded resolution. Displayed certificates and capability material must be reconfirmed for the exact product and order.',verified:'Verified company details',registry:'China registration no. 91510504MA67P35K4B · issued 8 Apr 2018 · long-term validity',markets:'International coordination',marketsText:'Nearest port listed: Luzhou Port. Public supplier data shows domestic sales remain the majority; overseas orders require destination-specific freight confirmation.',view:'View collection',brief:'Start a packaging brief',details:'Project details',detailsPlaceholder:'Product use, dimensions, artwork, material, printing, packing and delivery requirements',copy:'Copy brief & contact supplier'},
  zh:{source:'阿里供应商原始素材',notice:'图片来自供应商公开阿里店铺，并按页面实际加载的原始分辨率下载。证书与能力资料对具体产品是否适用、是否在有效期内，仍应在下单前再次确认。',verified:'企业核验信息',registry:'中国统一社会信用代码 91510504MA67P35K4B · 2018 年 4 月 8 日签发 · 长期有效',markets:'国际交付协同',marketsText:'公开资料列出的最近港口为泸州港。供应商销售仍以内销为主，海外订单需按目的地单独确认运输方案。',view:'查看产品集合',brief:'开始填写包装需求',details:'项目需求',detailsPlaceholder:'请填写用途、尺寸、设计稿、材料、印刷、装箱与交付要求',copy:'复制需求并联系供应商'},
  fr:{source:'Support original du fournisseur',notice:'Ces images proviennent de la boutique Alibaba publique du fournisseur et ont été téléchargées dans la résolution chargée d’origine. La portée et la validité des certificats doivent être reconfirmées pour chaque produit.',verified:'Données vérifiées de l’entreprise',registry:'Immatriculation chinoise 91510504MA67P35K4B · délivrée le 8 avril 2018 · durée illimitée',markets:'Coordination internationale',marketsText:'Port le plus proche indiqué : port de Luzhou. Les ventes nationales restent majoritaires ; le transport export doit être confirmé selon la destination.',view:'Voir la collection',brief:'Démarrer un brief packaging',details:'Détails du projet',detailsPlaceholder:'Usage, dimensions, fichier, matière, impression, conditionnement et livraison',copy:'Copier le brief et contacter le fournisseur'},
  de:{source:'Originalmaterial des Lieferanten',notice:'Die Bilder wurden aus dem öffentlichen Alibaba-Shop des Lieferanten in der tatsächlich geladenen Originalauflösung übernommen. Geltungsbereich und Laufzeit von Zertifikaten sind je Produkt erneut zu prüfen.',verified:'Geprüfte Unternehmensdaten',registry:'Chinesische Registriernummer 91510504MA67P35K4B · ausgestellt 08.04.2018 · unbefristet',markets:'Internationale Koordination',marketsText:'Nächstgelegener gelisteter Hafen: Luzhou. Der Inlandsumsatz überwiegt; Exportfracht muss je Zielort bestätigt werden.',view:'Kollektion ansehen',brief:'Verpackungsbriefing starten',details:'Projektdetails',detailsPlaceholder:'Verwendung, Maße, Daten, Material, Druck, Verpackung und Lieferung',copy:'Briefing kopieren und Lieferanten kontaktieren'},
  es:{source:'Material original del proveedor',notice:'Las imágenes se descargaron de la tienda pública de Alibaba en la resolución original cargada. El alcance y la vigencia de los certificados deben confirmarse para cada producto.',verified:'Datos empresariales verificados',registry:'Registro chino 91510504MA67P35K4B · expedido el 8 de abril de 2018 · vigencia indefinida',markets:'Coordinación internacional',marketsText:'Puerto más cercano indicado: Luzhou. Las ventas nacionales siguen siendo mayoritarias; el transporte de exportación se confirma por destino.',view:'Ver colección',brief:'Iniciar un brief de embalaje',details:'Detalles del proyecto',detailsPlaceholder:'Uso, medidas, diseño, material, impresión, embalaje y entrega',copy:'Copiar brief y contactar al proveedor'},
  it:{source:'Materiale originale del fornitore',notice:'Le immagini sono state scaricate dalla vetrina pubblica Alibaba nella risoluzione originale caricata. Ambito e validità dei certificati vanno riconfermati per ogni prodotto.',verified:'Dati aziendali verificati',registry:'Registrazione cinese 91510504MA67P35K4B · rilasciata 8 aprile 2018 · validità illimitata',markets:'Coordinamento internazionale',marketsText:'Porto più vicino indicato: Luzhou. Le vendite nazionali restano prevalenti; il trasporto export va confermato per destinazione.',view:'Vedi la collezione',brief:'Avvia un brief packaging',details:'Dettagli del progetto',detailsPlaceholder:'Uso, dimensioni, grafica, materiale, stampa, imballaggio e consegna',copy:'Copia il brief e contatta il fornitore'},
  ar:{source:'مادة أصلية من المورد',notice:'تم تنزيل الصور من متجر المورد العام على علي بابا بالدقة الأصلية المحمّلة. يجب إعادة تأكيد نطاق الشهادات وصلاحيتها للمنتج والطلب المحددين.',verified:'بيانات الشركة المتحقق منها',registry:'رقم التسجيل الصيني 91510504MA67P35K4B · صدر في 8 أبريل 2018 · صلاحية طويلة الأجل',markets:'التنسيق الدولي',marketsText:'أقرب ميناء مدرج هو ميناء لوتشو. تمثل المبيعات المحلية الحصة الأكبر، ويُؤكد شحن التصدير حسب الوجهة.',view:'عرض المجموعة',brief:'ابدأ موجز العبوة',details:'تفاصيل المشروع',detailsPlaceholder:'الاستخدام والمقاسات والتصميم والخامة والطباعة والتعبئة والتسليم',copy:'انسخ الموجز وتواصل مع المورد'},
  ru:{source:'Оригинальный материал поставщика',notice:'Изображения загружены из публичного магазина Alibaba в исходном разрешении страницы. Область действия и срок сертификатов нужно подтвердить для конкретного товара.',verified:'Проверенные данные компании',registry:'Регистрационный номер в Китае 91510504MA67P35K4B · выдан 08.04.2018 · бессрочно',markets:'Международная координация',marketsText:'Ближайший указанный порт — Лучжоу. Основная доля продаж внутренняя; экспортную перевозку согласуют для каждого направления.',view:'Открыть коллекцию',brief:'Начать бриф по упаковке',details:'Детали проекта',detailsPlaceholder:'Назначение, размеры, макет, материал, печать, упаковка и доставка',copy:'Скопировать бриф и связаться с поставщиком'},
  hi:{source:'सप्लायर की मूल सामग्री',notice:'चित्र सप्लायर के सार्वजनिक Alibaba स्टोर से पेज पर लोड हुई मूल रिज़ॉल्यूशन में डाउनलोड किए गए हैं। हर उत्पाद के लिए प्रमाणपत्र का दायरा और वैधता दोबारा जाँचें।',verified:'सत्यापित कंपनी विवरण',registry:'चीन पंजीकरण संख्या 91510504MA67P35K4B · 8 अप्रैल 2018 को जारी · दीर्घकालीन वैधता',markets:'अंतरराष्ट्रीय समन्वय',marketsText:'सूचीबद्ध निकटतम पोर्ट: लूझोउ पोर्ट। घरेलू बिक्री बहुमत में है; निर्यात मालभाड़ा गंतव्य के अनुसार पुष्टि करें।',view:'कलेक्शन देखें',brief:'पैकेजिंग ब्रीफ़ शुरू करें',details:'प्रोजेक्ट विवरण',detailsPlaceholder:'उपयोग, आकार, आर्टवर्क, सामग्री, प्रिंटिंग, पैकिंग और डिलीवरी',copy:'ब्रीफ़ कॉपी करें और सप्लायर से संपर्क करें'},
  id:{source:'Materi asli pemasok',notice:'Gambar diunduh dari toko Alibaba publik pemasok pada resolusi asli yang dimuat halaman. Cakupan dan masa berlaku sertifikat perlu dikonfirmasi kembali untuk produk terkait.',verified:'Data perusahaan terverifikasi',registry:'Nomor registrasi Tiongkok 91510504MA67P35K4B · terbit 8 April 2018 · berlaku jangka panjang',markets:'Koordinasi internasional',marketsText:'Pelabuhan terdekat yang tercantum: Luzhou. Penjualan domestik masih dominan; angkutan ekspor dikonfirmasi sesuai tujuan.',view:'Lihat koleksi',brief:'Mulai brief kemasan',details:'Detail proyek',detailsPlaceholder:'Penggunaan, ukuran, desain, bahan, cetak, pengemasan, dan pengiriman',copy:'Salin brief dan hubungi pemasok'},
};

const state = {email:'',type:'paperbag',quantity:'',details:'',status:'',error:''};
const featured = [
  ...paperIds.map(id=>allProducts.find(item=>item.id===id)).filter(Boolean),
  ...['nonwoven','paperbox','mailerbox','plasticbag'].flatMap(category=>allProducts.filter(item=>item.category===category).slice(0,2)),
];
const currentUi = () => ui[getLanguage()] || ui.en;

function navMarkup() {
  const links = [[route('/products/featured/'),'allProducts'],[route('/capabilities/custom-packaging/'),'capabilities'],[route('/capabilities/production/'),'process'],[route('/quality/'),'quality'],[route('/company/'),'company']];
  return `<header class="topbar source-navigation content-navigation">${wordmark(route('/'))}<nav id="nav" aria-label="${t('nav')}">${links.map(([href,key])=>`<a href="${href}">${t(key)}</a>`).join('')}</nav><div class="nav-actions">${languageSwitch()}<a class="button button-sm" href="${route('/request-quote/')}">${t('quote')} ↗</a><button class="menu" type="button" aria-controls="nav" aria-label="${t('menuOpen')}" aria-expanded="false">☰</button></div></header>`;
}

function productGrid() {
  return `<section class="content-products" aria-label="${t('allProducts')}">${featured.map(item=>`<a class="content-product" href="${productLink(item)}"><img src="${imagePath(item)}" alt="${esc(productTitle(item))}" loading="lazy"><span>${esc(t(item.category))}</span><h2>${esc(productTitle(item))}</h2><b>${t('viewDetails')} <span class="direction-arrow">→</span></b></a>`).join('')}</section><p class="content-collection-link"><a class="button" href="${categoryLink('all')}">${currentUi().view} · ${number(allProducts.length)} <span class="direction-arrow">→</span></a></p>`;
}

function companyDetails() {
  const l=currentUi();
  return `<section class="content-evidence"><article><span>01</span><h2>${l.verified}</h2><p>${l.registry}</p></article><article><span>02</span><h2>${l.markets}</h2><p>${l.marketsText}</p></article></section>`;
}

function quoteForm(page) {
  const l=currentUi();
  const message=()=>[t('inquiryHello'),t('email')+': '+state.email,t('productLabel')+': '+t(state.type),t('quantity')+': '+(state.quantity||t('pending')),l.details+': '+(state.details||t('inquiryDefault'))].join('\n');
  return `<section class="content-quote"><div><span class="kicker">${l.brief}</span><h2>${t('contactTitle')}</h2><p>${page.description}</p></div><form id="content-quote-form" novalidate><label>${t('email')}<input name="email" type="email" autocomplete="email" dir="ltr" value="${esc(state.email)}" required aria-invalid="${Boolean(state.error)}" aria-describedby="content-form-error"></label><p class="form-error" id="content-form-error" role="alert">${state.error?t(state.error):''}</p><label>${t('productType')}<select name="type">${['paperbag','nonwoven','paperbox','mailerbox','plasticbag','otherPackaging'].map(key=>`<option value="${key}" ${state.type===key?'selected':''}>${t(key)}</option>`).join('')}</select></label><label>${t('quantity')}<input name="quantity" value="${esc(state.quantity)}" placeholder="${t('quantityPlaceholder')}"></label><label>${l.details}<textarea name="details" rows="6" placeholder="${l.detailsPlaceholder}">${esc(state.details)}</textarea></label><button class="button" type="submit">${l.copy} ↗</button><p class="form-note" id="content-form-note" aria-live="polite">${formStatus(state.status,message())}</p></form></section>`;
}

function render() {
  const entity=entityFromLocation();
  const page=getContentPage(entity.type==='content'?entity.slug:'company',getLanguage());
  if(!page){ location.assign(route('/')); return; }
  metadata(page.title+' | LU Packaging',page.description);
  const l=currentUi();
  document.querySelector('#content-app').innerHTML=`${navMarkup()}<main><section class="content-hero"><div><span class="kicker">${page.eyebrow}</span><h1>${page.title}</h1><p>${page.description}</p><a class="text-link" href="${route('/request-quote/')}">${t('quote')} <span class="direction-arrow">→</span></a></div><figure class="content-media media-${page.layout}"><img src="${page.image}" alt="${esc(page.imageAlt)}" fetchpriority="high"><figcaption>${l.source}</figcaption></figure></section><section class="content-points section-shell">${page.points.map((point,index)=>`<article><span>${String(number(index+1)).padStart(2,'0')}</span><p>${point}</p></article>`).join('')}</section>${page.layout==='company'?companyDetails():''}${page.layout==='products'?productGrid():''}${page.layout==='quote'?quoteForm(page):''}<aside class="content-source-note section-shell"><strong>${l.source}</strong><p>${l.notice}</p><a href="${supplierUrl}" target="_blank" rel="noopener">${t('store')} ↗</a></aside>${page.layout!=='quote'?`<section class="content-cta section-shell"><span>${l.brief}</span><h2>${t('contactTitle')}</h2><a class="button inverse" href="${route('/request-quote/')}">${t('quote')} ↗</a></section>`:''}</main>${footer()}`;
  const menu=document.querySelector('.menu');
  menu.onclick=()=>{const open=document.querySelector('#nav').classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',t(open?'menuClose':'menuOpen'));menu.textContent=open?'×':'☰';};
  const form=document.querySelector('#content-quote-form');
  if(form){
    const message=()=>[t('inquiryHello'),t('email')+': '+state.email,t('productLabel')+': '+t(state.type),t('quantity')+': '+(state.quantity||t('pending')),l.details+': '+(state.details||t('inquiryDefault'))].join('\n');
    form.oninput=form.onchange=()=>{state.email=form.elements.email.value;state.type=form.elements.type.value;state.quantity=form.elements.quantity.value;state.details=form.elements.details.value;state.status='';document.querySelector('#content-form-note').innerHTML=formStatus('',message());};
    form.onsubmit=async event=>{event.preventDefault();state.error=emailError(form.elements.email,true);document.querySelector('#content-form-error').textContent=state.error?t(state.error):'';form.elements.email.setAttribute('aria-invalid',String(Boolean(state.error)));if(state.error){form.elements.email.focus();return;}state.status=await copyMessage(message());document.querySelector('#content-form-note').innerHTML=formStatus(state.status,message());};
  }
}

initLanguage(render);
